### ISSUE TITLE
Can i use this awesome plugin in a new project and it compatible with 17.x.x

### ISSUE THREAD

**Issue by chrisgate** [charlieduong94/joi-data-model#1]
Hi @charlieduong94 ,
Can i use this awesome plugin in a new project and it compatible with 17.x.x

Thanks in anticipation

Chris

**Comment by ctdio** [comment]
Yes, you can use this wherever you'd like! Not sure what you mean about being compatible with `17.x.x` though (perhaps you mean the joi version? It only goes up to `13.6.0` at the moment).

**Comment by mmcfarland-novetta** [comment]
FYI - this project seems to work with joi v14.3.1, but is not compatible with joi v17.x.x.
